In [1]:
import numpy as np

In [3]:
my_m = [[1,2,3,3,4],[3,5,6,7,8]]
my_m


[[1, 2, 3, 3, 4], [3, 5, 6, 7, 8]]

In [4]:
type(my_m)


list

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1,4)

array([[0.84790498, 0.01766621, 0.82188747, 0.83583727]])

In [10]:
np.random.randn(3,4)

array([[ 0.65604726,  1.37752326,  0.68601964,  0.37917473],
       [ 1.93712871, -1.77991996, -1.42102195, -1.59692639],
       [-1.02253124, -0.98193795,  1.07718176, -1.03008464]])

In [11]:
np.random.randint(1,101,8)

array([39, 92, 40, 85, 84, 69, 23, 38])

In [13]:
np.random.randint(1,101,[4,3])

array([[95, 16, 16],
       [ 8,  1, 67],
       [40, 41, 95],
       [46, 38, 33]])

In [16]:
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

When multiply the reshape value it should give same number as number of elements

In [18]:
arr.reshape(5,4) 

ValueError: ignored

In [19]:
arr = np.random.randint(0,202,10)
arr

array([  4,  74, 177,  57, 104,  68,  55, 151,  79, 113])

In [20]:
arr.max()

177

In [21]:
arr.min()

4

In [22]:
arr.mean()

88.2

In [24]:
arr.sum()

882

In [27]:
arr.argmin()

0

In [30]:
arr.dtype


dtype('int64')

In [31]:
ar = np.linspace(0,10,101)
ar

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])